export const flavors = [ 
    'almond',
    'apple',
    'apricot',
    'blackberry',
    'coffee',
    'cherry cola',
    'cherry soda', 
    'chocolate',
    'citron',
    'cranberry',
    'cream soda',
    'cucumber soda',
    'grape soda',
    'grapefruit', 
    'guarana',
    'lime',
    'mandarin orange',
    'mango',
    'melon',
    'peach',
    'pear',
    'papaya',
    'pineapple',
    'raspberry',
    'strawberry',
    'watermelo',
    'orange juice',
    'cola-caramel',
    'lemon juice',
    'apple juice',
    'beet juice', 
    'blueberry juice',
    'cranberry juice',
    'carrot juice',
    'grape juice',
    'grapefruit juice',
    'orange juice',
    'mocochinchi juice',
]
